export const FETCHING_FRIEND = 'FETCHING_FRIEND';
export const FETCHING_FRIEND_SUCCESS = 'FETCHING_FRIEND_SUCCESS';
export const FETCHING_FRIEND_FAILURE = 'FETCHING_FRIEND_FAILURE';

export const UPDATING_FRIEND = 'UPDATING_FRIEND';
export const UPDATING_FRIEND_SUCCESS = 'UPDATING_FRIEND_SUCCESS';
export const UPDATING_FRIEND_FAILURE = 'UPDATING_FRIEND_FAILURE';

export const DELETING_FRIEND = 'DELETING_FRIEND';
export const DELETING_FRIEND_SUCCESS = 'DELETING_FRIEND_SUCCESS';
export const DELETING_FRIEND_FAILURE = 'DELETING_FRIEND_FAILURE';

export const SAVING_FRIEND = 'SAVING_FRIEND';
export const SAVING_FRIEND_SUCCESS = 'SAVING_FRIEND_SUCCESS';
export const SAVING_FRIEND_FAILURE = 'SAVING_FRIEND_FAILURE';

export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
